services:
#  kamu:
#    image: ghcr.io/kamu-data/kamu-base:latest-with-data
#    container_name: "kamu"
#    ports:
#      - "3080:3080"
#      - "39189:39189"
#    command: kamu system api-server --http-port 3080 --address 0.0.0.0

  api:
    build:
      context: ./kamu-bacalhau
      dockerfile: ./Dockerfile
    ports:
      # API port
      - 3000:3000
      # Kamu Http Gateway
      - 3080:3080
      # Kamu UI
      - 36083:36083
      # Swarm listens on all interfaces, so is remotely reachable.
      - 4001:4001/tcp
      - 4001:4001/udp

      # The following ports only listen on the loopback interface, so are not remotely reachable by default.
      # If you want to override these or add more ports, see https://docs.docker.com/compose/extends/ .

      # API port, which includes admin operations, so you probably don't want this remotely accessible.
      - 5001:5001

      # HTTP Gateway
      - 8080:8080
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./kamu-bacalhau:/app
      - /app/node_modules
    command: ./start.sh

volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse: